name: build-docker

on:
  push:
    tags: '*'



jobs:

  buildx:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=version::${TAG}
            echo ::set-output name=sourcetag::${TAG}
          else
            echo ::set-output name=version::dev
            echo ::set-output name=sourcetag::HEAD
          fi
          echo ::set-output name=docker_image::ghcr.io/ejsmit/minio
          echo ::set-output name=docker_username::ejsmit
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: minio/minio
          ref: ${{ steps.prepare.outputs.version }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ejsmit
          password: ${{ secrets.CR_PAT }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ steps.prepare.outputs.docker_image }}:latest
            ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



